#
# Configuration file for polis backend (data collection, storage, and indexing)
#

DEFAULT = {
  # The absolute path that includes the "polis" directory
  "root_dir": ""
}

c = {
  "sqlite3":{
    # Destination location for the SQLite3 database. Default is project_root/sql/polis.db
    # SQLite3 db houses person and city data used to drive web searches
    "db_file": DEFAULT["root_dir"] + "/sql/polis.db",
    # Destination location for the SQLite3 schema. Default is project_root/sql/schema.sql
    "schema": DEFAULT["root_dir"] + "/sql/schema.sql"
  },
  "mongodb": {
    # Specify the name of the primary database
    "database": "polis_data",
    # Specify the collections used in MongoDB instance
    "collections": ["twitter", "rss"]
  },
  "elasticsearch": None,
  "twitter":{
    # Rate limit is the min time between requests to avoid throttling, in seconds
    "rate_limit": 5,
    # Frequency is the list of scheduled request CYCLES, in hours of the day.
    # e.g., "0,6,12,18" will trigger at midnight, 6AM, noon, and 6PM
    "frequency": "0,6,12,18",
    "daemon": "twitterbot.py",
    "logfile": "tw_log.txt"
  },
  "rss":{
    # Rate limit is the min time between requests to (hopefully) avoid throttling, in seconds
    "rate_limit": 20,
    # Frequency is the list of scheduled request CYCLES, in hours of the day.
    # e.g., "0,6,12,18" will trigger at midnight, 6AM, noon, and 6PM
    "frequency": "5,17",
    "gnews_url": "https://news.google.com/news?output=rss&q=",
    # Lower bound in the (inclusive) cutoff for <p/> section lengths when fetching content
    # Used to remove cruft, headers, etc.
    "lower_bound": 50,
    "daemon": "rssbot.py",
    "logfile": "rss_log.txt"
  },
  "nlp":{
    # default directory within "root_dir" to house all NLP data
    "default_dir": DEFAULT["root_dir"] + "/nlp_data/",
    "twitter": {
      # weighted training set generated by the system
      "train": "en-twitter-train.tsv",
      # optimized cutoff value for the weighted training set
      "co_value": 4082,
      # base file name for the training sets producted by the system
      "temp_fl": "_tw_train.tsv"
    },
    "rss":{
      # weighted training set generated by the system
      "train": "en-rss-train.tsv",
      # optimized cutoff value for the weighted training set
      "co_value": 500,
      # base file name for the training sets producted by the system
      "temp_fl": "_rss_train.tsv"
    },
    # genetic optimization algorithm variables
    "go_vars": {
      # number of independent selection events
      "num_se": 40,
      # training model evalutation upper bound
      "score_threshold": 0.95,
      # fraction of trainiing set to exclude as a test set
      "frac_test": 0.1,
      # number of evalutation cycles per event
      "num_cycles": 30,
      # number by which to divide (remaining) training set for each evalutation round 
      "sub_div": 20
    }
  },
  "webapp":{
    "username": "admin",
    "default_pwd": "",
    "secret_key": ""
  }
}
